services:
  ai-tool:
    build: .
    container_name: industrial_vision_tester
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_HOME=/usr/local/cuda
    volumes:
      # Sincroniza tu código y tus imágenes en tiempo real
      - ./dino.py:/app/dino.py
      - ./datasets:/app/datasets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    tty: true