services:  
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3-management'
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck: 
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: 
      - app-network
  redis:
    container_name: redis
    image: 'redis:alpine'
    ports:
    - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    volumes:
      - redis-data:/data
    networks: 
      - app-network
  blender-tool:
    container_name: auto-photo-taker-3000
    build: 
      context: ./blender
      dockerfile: Dockerfile
    environment:
      - STAGING_PATH=/staging
      - TZ=America/Hermosillo
    volumes:
      - ./blender/scenes:/scenes       
      - ./blender/staging:/staging      
    restart: unless-stopped
    depends_on: 
      rabbitmq: 
        condition: service_healthy
      redis: 
        condition: service_started
    networks:
      - app-network

  ai-tool:
    build:
      context: ./anotation        
      dockerfile: Dockerfile
    container_name: industrial_vision_tester
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_HOME=/usr/local/cuda
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_URL=redis://redis:6379
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis: 
        condition: service_started
    volumes:
      - ./anotation/dinoWorker.py:/app/dinoWorker.py
      - ./anotation/datasets:/app/datasets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    tty: true
    networks:
      - app-network

  backend_server:
    build:
      context: ./backend           
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env             
    command: sleep infinity
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: kitting_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d kitting_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis-data:
  temp-data: